steps:

- id: Check Docker triggers
  name: gcr.io/cloud-builders/gcloud
  waitFor: ['-']
  entrypoint: bash
  args:
  - -exc
  - |
    apt-get update
    apt-get install jq -y
    ./publishIntegration.bash 1a6b8f27-3ec0-4ad2-827b-6e1fa2e21d06